# Generated by Django 4.2.7 on 2023-11-19 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_bloodrequest_request_by_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_delete_patient_patients_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patients',
            new_name='patientsdata',
        ),
    ]
