# Generated by Django 4.2.7 on 2023-11-19 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientsdatas_remove_patientsdata_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood', '0006_alter_bloodrequest_request_by_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientsdata',
        ),
        migrations.AddField(
            model_name='patientsdatas',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
