# Generated by Django 4.2.7 on 2023-11-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_rename_user_patientsdatas_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsdatas',
            old_name='user_id',
            new_name='user',
        ),
    ]
