# Generated by Django 4.2.7 on 2023-11-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_rename_user_id_patientsdatas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsdatas',
            name='DOB',
        ),
    ]
